# Site settings
title: Swirl Documentation
email: support@swirl.today
description: >- # this means to ignore newlines until "baseurl:"
  Swirl is open source software that simultaneously searches multiple content sources and returns AI ranked results.
baseurl: "/swirl-search" # the subpath of your site, e.g. /blog. If there's no subpath, leave it as an empty string.
url: "https://swirlai.github.io/swirl-search" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
remote_theme: mattgraham/midnight
plugins:
  - jekyll-feed # The jekyll-feed plugin is commonly used to generate an Atom (RSS-like) feed of your posts.
  - jekyll-remote-theme


# Exclude from processing
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
