# Site settings
title: Swirl Documentation
email: support@swirl.today

# Build settings
remote_theme: pages-themes/midnight
plugins:
  - jekyll-remote-theme

# Exclude from processing
# The following items will not be processed, by default. Create a custom list to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock