# Site settings
title: Swirl Documentation
description: "One search box to find it all"
repository: "swirlai/swirl-search"
url: https://github.com/swirlai/swirl-search
baseurl: "" # the subpath of your site, e.g. /blog

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/swirl-logo.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.ico"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Heading anchor links appear on hover over h1-h6 tags in page content
heading_anchors: true

# For copy button on code
enable_copy_code_button: true

# External navigation links
nav_external_links:
  - title: Swirl on GitHub
    url: https://github.com/swirlai/swirl-search
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true
  - title: Swirl.Today
    url: https://swirl.today/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true

# Aux links for the upper right navigation
aux_links:
  "Swirl on GitHub":
    - "//github.com/swirlai/swirl-search"
aux_links_new_tab: true # Makes Aux links open in a new tab. Default is false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

callouts_level: loud # or quiet
callouts:
  highlight:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red

# Site search configs (TO DO:  adjust these or remove this section)
# search:

exclude:
 # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

# Build settings
markdown: kramdown
remote_theme: "just-the-docs/just-the-docs"
plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-include-cache
  - jemoji

# Kramdown settings
kramdown:
  smart_quotes: [apos, apos, quot, quot]
