name: Docker Build for amd64

# Build amd64 docker image for SWIRL
# comment to start build

on:
  push:
    # only trigger on branches, not on tags
    branches: 'main'

jobs:

  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build -t swirlai/swirl-search:latest-amd64 .
    - name: Publish the image to DockerHub
      run: docker push swirlai/swirl-search:latest-amd64
