name: Latest Spyglass Docker Build

on:
  workflow_dispatch:

jobs:

  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image   
      run: docker build -t dnicoswirl/spyglass:latest  -f Dockerfile.spg
    - name: Push the Docker image   
      run: docker push dnicoswirl/spyglass
