name: Ingegration UI Tests
## Do we need to set this to something? SWIRL_TEST_HOST
## or this? ALLOWED_HOSTS=localhost,host.docker.internal
on:
  push:
    # only trigger on branches, not on tags
    branches: 'ui-cicd-test-dev'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
            python-version: '3.10'
            cache: 'pip' # caching pip stuff
    ##########################################	    
    # Update apt w/ retries, and install erlang for rabbit
    ##########################################	    
    - name: Update apt
      run: sudo apt -o Acquire::Retries=3 update
    - name: Run Install erlang
      run: sudo apt -o Acquire::Retries=3 install -y erlang
    ##########################################	    
    # Install swirl
    ##########################################
    - name: Run Install rabbitmq-server
      run: sudo apt install -y rabbitmq-server    
    - name: Run Install Swirl
      run: ./install.sh
    - name: Set up SWIRL
      run: python swirl.py setup
    - name: Run Install Galaxy
      run: ./install-ui.sh -p
    ##########################################	    
    # Pull selenium image
    ##########################################
    - name: Pull selenium image
      run: docker pull seleniarm/standalone-chromium:latest
    ##########################################	    
    # Run selenium image
    ##########################################
    - name: Run selenium image
      run: docker run -p 4444:4444 -p 5900:5900 -p 7900:7900 --shm-size 2g seleniarm/standalone-chromium:latest
    ##########################################	    
    # Start Swirl
    ##########################################
    - name: Start up SWIRL
      run: python swirl.py start
    ##########################################	    
    # Run UI tests
    ##########################################
    - name: Run Integrated API tests
      run: docker run --net=host -t swirlai/swirl-search:latest-ui-automation sh -c "behave **/*/search_core.feature --tags=ui_agile_test"
