name: Smoke Test
on:
  push:
    # only trigger on branches, not on tags
    # add a comment to trigger
    branches: 'auto-test-integration'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
            python-version: '3.10'
            cache: 'pip' # caching pip dependencie
    - name: depend
      run: ./install.sh
